# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
    ]
